# Generated by Django 5.2.17 on 2026-09-15 09:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('botanical_name', models.CharField(blank=True, max_length=200)),
                ('part_used', models.CharField(blank=True, max_length=100)),
                ('default_unit', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.productcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('handle', models.SlugField(blank=True, help_text='Used as the Shopify product handle. Auto-filled from the name if left blank.', max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('indications', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True, help_text='Shopify product description (HTML allowed).')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated, e.g. "vitamins, immunity".', max_length=255)),
                ('enlistment_number', models.CharField(blank=True, max_length=100)),
                ('form', models.CharField(blank=True, max_length=100)),
                ('pack_size', models.CharField(blank=True, max_length=100)),
                ('unit_of_measure', models.CharField(choices=[('PIECE', 'Piece'), ('BOTTLE', 'Bottle'), ('BOX', 'Box'), ('CASE', 'Case'), ('KG', 'Kilogram'), ('GRAM', 'Gram'), ('LITRE', 'Litre'), ('ML', 'Millilitre'), ('OTHER', 'Other')], default='PIECE', max_length=12)),
                ('units_per_case', models.PositiveIntegerField(default=1)),
                ('serving_size', models.CharField(blank=True, max_length=100)),
                ('strength_basis', models.CharField(blank=True, choices=[('PER_CAPSULE', 'Per capsule'), ('PER_SERVING', 'Per serving'), ('PER_TABLET', 'Per tablet'), ('PER_ML', 'Per ml'), ('OTHER', 'Other')], max_length=20)),
                ('base_retail_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Shown as the "was" price on Shopify. Leave blank if not discounted.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weight_grams', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('shelf_life_months', models.PositiveIntegerField(default=0)),
                ('hs_code', models.CharField(blank=True, max_length=30)),
                ('default_reorder_point', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('default_reorder_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('allow_fractional_quantity', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='manufacturers.manufacturer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ['name', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('is_medicinal', models.BooleanField(default=False)),
                ('extract_ratio', models.CharField(blank=True, max_length=100)),
                ('equivalent_to', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='products.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('barcode',), name='unique_product_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='unique_product_ingredient'),
        ),
    ]
