# Generated by Django 5.2.17 on 2026-10-05 14:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productretailprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How much is in one pack, in the unit of measure: e.g. 60 (capsules), 100 (ml) or 300 (grams).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('PIECE', 'Unit'), ('BOTTLE', 'Bottle'), ('BOX', 'Box'), ('CASE', 'Case'), ('KG', 'Kilogram'), ('GRAM', 'Gram'), ('LITRE', 'Litre'), ('ML', 'Millilitre'), ('OTHER', 'Other')], default='PIECE', max_length=12),
        ),
    ]
