# Generated by Django 5.2.17 on 2026-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_seed_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopify_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='shopify_product_id',
            field=models.CharField(blank=True, db_index=True, help_text='Set when the product is imported from Shopify.', max_length=100),
        ),
    ]
