# Generated by Django 5.2.17 on 2026-09-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_warehouse', '0002_alter_location_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('OWN', 'Owned'), ('SUPPLIER', 'Supplier'), ('DISTRIBUTOR', 'Distributor'), ('CUSTOMER', 'Customer'), ('SHOPIFY', 'Shopify'), ('TRANSIT', 'In Transit')], max_length=20),
        ),
    ]
