# Generated by Django 5.2.17 on 2026-09-17 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_warehouse', '0003_alter_location_location_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('OWN', 'Owned'), ('SUPPLIER', 'Supplier'), ('DISTRIBUTOR', 'Distributor'), ('CUSTOMER', 'Customer'), ('SHOPIFY', 'Shopify'), ('TRANSIT', 'In Transit'), ('UNALLOCATED', 'Unallocated')], max_length=20),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'inventories',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='inventory',
            field=models.ForeignKey(blank=True, help_text='Which region this warehouse belongs to. Required for owned warehouses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='owner_warehouse.inventory'),
        ),
    ]
