# Generated by Django 5.2.17 on 2026-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_warehouse', '0005_migrate_distributor_stock_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='distributor_profile',
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('OWN', 'Owned'), ('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('SHOPIFY', 'Shopify'), ('TRANSIT', 'In Transit'), ('UNALLOCATED', 'Unallocated')], max_length=20),
        ),
    ]
