# Generated by Django 5.2.17 on 2026-09-29 07:41

from django.db import migrations, models


def drop_legacy_customer_data(apps, schema_editor):
    """The customers app was removed and 0001 no longer creates
    Location.customer, so fresh databases never have it. Databases
    migrated before the removal still carry the customer_id column and
    the customers_customer table — drop both here."""
    connection = schema_editor.connection
    Location = apps.get_model("owner_warehouse", "Location")
    table = Location._meta.db_table

    with connection.cursor() as cursor:
        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table)
        }
        tables = set(connection.introspection.table_names(cursor))

    if "customer_id" in columns:
        if connection.vendor == "sqlite":
            # Rebuilding from the migration state (which has no customer
            # field) copies every other column and drops customer_id.
            schema_editor._remake_table(Location)
        else:
            schema_editor.execute(
                f"ALTER TABLE {schema_editor.quote_name(table)} "
                f"DROP COLUMN {schema_editor.quote_name('customer_id')}"
            )

    if "customers_customer" in tables:
        schema_editor.execute("DROP TABLE customers_customer")

    schema_editor.execute(
        "DELETE FROM django_migrations WHERE app = 'customers'"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('owner_warehouse', '0006_remove_location_distributor_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('OWN', 'Owned'), ('SUPPLIER', 'Supplier'), ('SHOPIFY', 'Shopify'), ('TRANSIT', 'In Transit'), ('UNALLOCATED', 'Unallocated')], max_length=20),
        ),
        migrations.RunPython(drop_legacy_customer_data, migrations.RunPython.noop),
    ]
