# Generated by Django 5.2.17 on 2026-09-21 09:43

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributors', '0002_distributorprofile_upfront_payment_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorStockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(blank=True, help_text='Lot/batch label. Not unique on its own — every split of this same lot across warehouses keeps the same batch number, so it always traces back to one delivery.', max_length=100)),
                ('received_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('quantity_remaining', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reference', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'distributor stock batches',
                'ordering': ['expiry_date', 'received_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributorStockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('movement_type', models.CharField(choices=[('RECEIVED', 'Received'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributorStockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('distributor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='distributors.distributorprofile')),
            ],
            options={
                'ordering': ['product__name', 'location__name'],
            },
        ),
    ]
