# Generated by Django 5.2.17 on 2026-09-21 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor_inventory', '0001_initial'),
        ('distributor_warehouse', '0001_initial'),
        ('distributors', '0002_distributorprofile_upfront_payment_percentage'),
        ('products', '0002_product_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorstockbalance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='distributor_warehouse.distributorlocation'),
        ),
        migrations.AddField(
            model_name='distributorstockbalance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributor_stock_balances', to='products.product'),
        ),
        migrations.AddField(
            model_name='distributorstockbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributorstockbatch',
            name='distributor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='distributors.distributorprofile'),
        ),
        migrations.AddField(
            model_name='distributorstockbatch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='distributor_warehouse.distributorlocation'),
        ),
        migrations.AddField(
            model_name='distributorstockbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributor_stock_batches', to='products.product'),
        ),
        migrations.AddField(
            model_name='distributorstockbatch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributorstockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='For a RECEIVED movement, the batch it created. For stock leaving a warehouse, the batch it was drawn from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='distributor_inventory.distributorstockbatch'),
        ),
        migrations.AddField(
            model_name='distributorstockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributorstockmovement',
            name='distributor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='distributors.distributorprofile'),
        ),
        migrations.AddField(
            model_name='distributorstockmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='distributor_warehouse.distributorlocation'),
        ),
        migrations.AddField(
            model_name='distributorstockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributor_stock_movements', to='products.product'),
        ),
        migrations.AddField(
            model_name='distributorstockmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='distributor_warehouse.distributorlocation'),
        ),
        migrations.AddField(
            model_name='distributorstockmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='distributorstockbalance',
            constraint=models.UniqueConstraint(fields=('product', 'location'), name='unique_distributor_stock_balance_per_product_location'),
        ),
    ]
