# Generated by Django 5.2.17 on 2026-09-29 07:41

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_inventory', '0002_initial'),
        ('distributor_warehouse', '0001_initial'),
        ('distributors', '0002_distributorprofile_upfront_payment_percentage'),
        ('products', '0002_product_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment'), ('SOLD', 'Sold to Sub-Distributor')], max_length=20),
        ),
        migrations.CreateModel(
            name='SubDistributorSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_distributor_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('sale_date', models.DateField(default=datetime.date.today)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('distributor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_distributor_sales', to='distributors.distributorprofile')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_distributor_sales', to='distributor_warehouse.distributorlocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_distributor_sales', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
    ]
