# Generated by Django 5.2.17 on 2026-09-29 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_inventory', '0003_sub_distributor_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdistributorsale',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The batch this stock was drawn from. Only blank on sales recorded before sales were tied to a batch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_distributor_sales', to='distributor_inventory.distributorstockbatch'),
        ),
    ]
