# Generated by Django 5.2.17 on 2026-09-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_inventory', '0004_sub_distributor_sale_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdistributorsale',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Receipt, online transfer screenshot, photo — proof the sub-distributor paid. Blank means payment not received yet.', null=True, upload_to='sub_distributor_payments/'),
        ),
        migrations.AddField(
            model_name='subdistributorsale',
            name='sale_group',
            field=models.UUIDField(blank=True, db_index=True, help_text='Shared by the sale records of one hand-off split across several batches, so one payment proof covers all of them.', null=True),
        ),
    ]
