# Generated by Django 5.2.17 on 2026-09-17 11:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_manufacturerorder_manufacturerorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='upfront_payment_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="How much of an order's total is owed before shipping (from them), vs after receiving. 0 = pay only after receiving, 100 = pay in full before shipping, anything in between is a split.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='invoice_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='invoice_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_manufacturer_order_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='invoice_file',
            field=models.FileField(blank=True, help_text="The Manufacturer's own invoice document, as they gave it to us.", null=True, upload_to='manufacturer_order_invoices/'),
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='outcome_note',
            field=models.TextField(blank=True, help_text='Why this was disputed or refunded.'),
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='When the goods physically arrived from the Manufacturer.', null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerorder',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('GOOD', 'Good — no issues'), ('DISPUTED', 'Under discussion'), ('REFUNDED', 'Refunded')], default='SENT', max_length=20),
        ),
        migrations.CreateModel(
            name='ManufacturerOrderPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_at', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='manufacturers.manufacturerorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
