# Generated by Django 5.2.17 on 2026-09-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_brand_default_low_stock_threshold_and_more'),
        ('manufacturers', '0004_migrate_closed_status_to_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerorder',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer_orders', to='core.brand'),
        ),
    ]
