# Generated by Django 5.2.17 on 2026-09-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0005_manufacturerorder_brand'),
        ('requests', '0003_purchaseorderpayment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerorderitem',
            name='source_purchase_order_item',
            field=models.ForeignKey(blank=True, help_text='The Distributor purchase order line this was ordered to restock, if it was created that way.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_order_items', to='requests.purchaseorderitem'),
        ),
    ]
