# Generated by Django 5.2.17 on 2026-09-29 11:14

from django.db import migrations, models


def classify_existing_payments(apps, schema_editor):
    """Payments recorded before this change had no kind: one made before
    the goods arrived (or while they still haven't) was an advance,
    anything after was the final payment."""
    Payment = apps.get_model("manufacturers", "ManufacturerOrderPayment")
    Order = apps.get_model("manufacturers", "ManufacturerOrder")

    for payment in Payment.objects.select_related("order"):
        received_at = payment.order.received_at
        payment.kind = (
            "ADVANCE"
            if received_at is None or payment.paid_at < received_at.date()
            else "FINAL"
        )
        payment.save(update_fields=["kind"])

    Order.objects.filter(payments__kind="ADVANCE").update(pays_advance=True)


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0006_manufacturerorderitem_source_purchase_order_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturerorderpayment',
            options={'ordering': ['paid_at', 'created_at']},
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='pays_advance',
            field=models.BooleanField(blank=True, help_text='The Owner\'s answer to "Are you paying in advance?" right after placing the order. Blank until answered.', null=True),
        ),
        migrations.AddField(
            model_name='manufacturerorderpayment',
            name='kind',
            field=models.CharField(choices=[('ADVANCE', 'Advance'), ('FINAL', 'Final')], default='FINAL', max_length=10),
        ),
        migrations.AddField(
            model_name='manufacturerorderpayment',
            name='proof',
            field=models.FileField(blank=True, help_text='Bank slip, screenshot, etc. Required for every new payment; only blank on payments recorded before proofs existed.', null=True, upload_to='manufacturer_order_payments/'),
        ),
        migrations.RunPython(classify_existing_payments, migrations.RunPython.noop),
    ]
