# Generated by Django 5.2.17 on 2026-10-01 11:07

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0007_advance_and_final_payments'),
        ('products', '0003_productbottleprice'),
        ('requests', '0005_purchaseorder_agreement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturerorderitem',
            options={'ordering': ['product__name', 'bottle_size']},
        ),
        migrations.RemoveConstraint(
            model_name='manufacturerorderitem',
            name='unique_product_per_manufacturer_order',
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='po_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the Request to Quote became a Purchase Order.', null=True),
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='quote_file',
            field=models.FileField(blank=True, help_text="The Manufacturer's reply to our Request to Quote, with their real prices.", null=True, upload_to='manufacturer_order_quotes/'),
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='quoted_at',
            field=models.DateTimeField(blank=True, help_text="When the Manufacturer's quoted prices were entered.", null=True),
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='terms',
            field=models.TextField(blank=True, help_text='Terms and conditions printed on the Request to Quote / Purchase Order.'),
        ),
        migrations.AddField(
            model_name='manufacturerorderitem',
            name='bottle_size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, '30 capsules'), (60, '60 capsules'), (90, '90 capsules'), (120, '120 capsules')], help_text='Capsules per bottle. Blank for products not sold by capsule count.', null=True),
        ),
        migrations.AddField(
            model_name='manufacturerorderitem',
            name='requested_unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The price we asked for on the Request to Quote (blank = asked them to quote).', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='manufacturerorder',
            name='status',
            field=models.CharField(choices=[('QUOTE', 'Request to Quote'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('GOOD', 'Good — no issues'), ('DISPUTED', 'Under discussion'), ('REFUNDED', 'Refunded')], default='SENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='manufacturerorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Number of bottles (units).', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='manufacturerorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The current agreed price per bottle. Blank only on a Request to Quote.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='manufacturerorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'bottle_size'), name='unique_product_size_per_manufacturer_order'),
        ),
    ]
