# Generated by Django 5.2.17 on 2026-10-02 11:28

from django.db import migrations, models


def keep_typed_invoice_numbers(apps, schema_editor):
    """Invoice numbers used to be typed in by hand from the Manufacturer's
    invoice — keep them as the Manufacturer's reference now that our own
    INV-<BRAND>-0001 numbers are generated."""
    ManufacturerOrder = apps.get_model("manufacturers", "ManufacturerOrder")
    for order in ManufacturerOrder.objects.exclude(invoice_number=""):
        order.supplier_invoice_ref = order.invoice_number
        order.save(update_fields=["supplier_invoice_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0010_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerorder',
            name='supplier_invoice_ref',
            field=models.CharField(blank=True, help_text="The invoice number printed on the Manufacturer's own invoice, if any.", max_length=100),
        ),
        migrations.AlterField(
            model_name='manufacturerorder',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Our own invoice number, generated on receipt: INV-<BRAND>-0001.', max_length=100),
        ),
        migrations.RunPython(keep_typed_invoice_numbers, migrations.RunPython.noop),
    ]
