# Generated by Django 5.2.17 on 2026-10-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0011_invoice_numbering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturerorder',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
