# Generated by Django 5.2.17 on 2026-10-07 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0013_manufacturer_logo'),
        ('products', '0008_product_allergen_info_product_key_benefits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('stage', models.CharField(choices=[('REQUEST', 'Request to Quote'), ('QUOTE', "Manufacturer's quote"), ('COUNTER', 'Our counter-offer'), ('PURCHASE_ORDER', 'Purchase Order'), ('INVOICE', "Manufacturer's invoice")], max_length=20)),
                ('message', models.TextField(blank=True, help_text='What was said with this step — our note, or what the Manufacturer replied.')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='manufacturer_order_revisions/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='manufacturers.manufacturerorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='OrderRevisionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bottle_size', models.PositiveSmallIntegerField(blank=True, choices=[(30, '30 capsules'), (60, '60 capsules'), (90, '90 capsules'), (120, '120 capsules')], null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=3, help_text='Blank = no price given (please quote).', max_digits=18, null=True)),
                ('removed', models.BooleanField(default=False, help_text='This line was dropped from the order at this step.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='The live order line; blank once that line was dropped from the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_lines', to='manufacturers.manufacturerorderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturers.orderrevision')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product__name', 'bottle_size'],
            },
        ),
        migrations.AddConstraint(
            model_name='orderrevision',
            constraint=models.UniqueConstraint(fields=('order', 'number'), name='unique_revision_number_per_manufacturer_order'),
        ),
    ]
