# Generated by Django 5.2.17 on 2026-09-10 11:49

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('enlistment_number', models.CharField(blank=True, max_length=100)),
                ('ntn', models.CharField(blank=True, max_length=50)),
                ('strn', models.CharField(blank=True, max_length=50)),
                ('base_currency', models.CharField(default='PKR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=50)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('default_country', models.CharField(default='PK', max_length=2)),
                ('default_low_stock_threshold', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/logos/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
