# Generated by Django 5.2.17 on 2026-09-03 11:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('enlist_number', models.CharField(blank=True, max_length=100)),
                ('ntn', models.CharField(blank=True, max_length=50)),
                ('stn', models.CharField(blank=True, max_length=50)),
                ('base_currency', models.CharField(default='PKR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=50)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('default_conutry', models.CharField(default='PK', max_length=2)),
                ('default_low_stock_threshold', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('PO', 'Purchase Order'), ('GRN', 'Goods Receipt'), ('MOV', 'Stock Movement'), ('TRF', 'Transfer'), ('REQ', 'Stock Request'), ('ORD', 'Order'), ('DSP', 'Dispatch'), ('INV', 'Invoice'), ('RCPT', 'Receipt'), ('CRN', 'Credit Note'), ('RET', 'Return'), ('EXP', 'Expense')], max_length=10)),
                ('prefix', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('padding', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_sequences', to='core.company')),
            ],
            options={
                'ordering': ['-year', 'document_type'],
                'constraints': [models.UniqueConstraint(fields=('company', 'document_type', 'year'), name='unique_company_document_sequence'), models.CheckConstraint(condition=models.Q(('next_number__gte', 1)), name='document_sequence_positive_number')],
            },
        ),
        migrations.CreateModel(
            name='EquityPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('share_percentage', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('100.0000'))])),
                ('active_from', models.DateField()),
                ('active_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equity_partner', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('active_to__isnull', True), ('active_to__gte', models.F('active_from')), _connector='OR'), name='equity_partner_valid_dates'), models.CheckConstraint(condition=models.Q(('share_percentage__gt', 0), ('share_percentage__lte', 100)), name='equity_partner_valid_share')],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked')], default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_fiscal_periods', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_periods', to='core.company')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_fiscal_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('company', 'year', 'month'), name='unique_company_fiscal_period'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='fiscal_period_valid_month')],
            },
        ),
    ]
