# Generated by Django 5.2.17 on 2026-09-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='default_low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='enlistment_number',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='ntn',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='strn',
        ),
    ]
