# Generated by Django 5.2.17 on 2026-10-01 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_brand_default_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='primary_color',
            field=models.CharField(default='#1f7a4d', help_text="Theme colour for this brand's Requests to Quote and Purchase Orders.", max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Pick a colour or enter a hex code like #1f7a4d.')]),
        ),
    ]
