# Generated by Django 5.2.17 on 2026-09-21 09:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributors', '0002_distributorprofile_upfront_payment_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('distributor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='distributors.distributorprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'distributor inventories',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DistributorLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('UNALLOCATED', 'Unallocated')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('area_square_feet', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('capacity_units', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('distributor_inventory', models.ForeignKey(blank=True, help_text='Which region this warehouse belongs to. Required for a warehouse.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='distributor_warehouse.distributorinventory')),
                ('distributor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributor_locations', to='distributors.distributorprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='distributorinventory',
            constraint=models.UniqueConstraint(fields=('distributor_profile', 'code'), name='unique_distributor_inventory_code'),
        ),
        migrations.AddConstraint(
            model_name='distributorlocation',
            constraint=models.UniqueConstraint(fields=('distributor_profile', 'code'), name='unique_distributor_location_code'),
        ),
        migrations.AddConstraint(
            model_name='distributorlocation',
            constraint=models.CheckConstraint(condition=models.Q(('area_square_feet__gte', 0), ('capacity_units__gte', 0)), name='distributor_location_nonnegative_capacity'),
        ),
    ]
