# Generated by Django 5.2.17 on 2026-09-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('OWN', 'Owned'), ('SUPPLIER', 'Supplier'), ('DISTRIBUTOR', 'Distributor'), ('CUSTOMER', 'Customer'), ('SHOPIFY', 'Shopify')], max_length=20),
        ),
    ]
