# Generated by Django 5.2.17 on 2026-09-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_inventory', '0003_stockbatch_stockmovement_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Your own lot/batch label, e.g. BV-GL-AML-001 (Brand-Manufacturer-Product-Sequence). Not unique on its own — every split of this same lot across warehouses keeps the same batch number, so it always traces back to one delivery.', max_length=100),
        ),
    ]
