# Generated by Django 5.2.17 on 2026-09-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('owner_inventory', '0004_stockbatch_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='source_batch',
            field=models.ForeignKey(blank=True, help_text='The canonical Batch this lot traces back to, when it came from a Manufacturer Purchase Order. Not set for stock added manually (e.g. the Add Inventory form).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='batches.batch'),
        ),
    ]
