# Generated by Django 5.2.17 on 2026-09-30 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_inventory', '0005_stockbatch_source_batch'),
        ('requests', '0003_purchaseorderpayment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='shipped_for',
            field=models.ForeignKey(blank=True, help_text="For a lot sitting in Transit: the Distributor purchase order line it was shipped on, so only that order's receipt can draw it down — two orders for the same product never swap batches.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transit_batches', to='requests.purchaseorderitem'),
        ),
    ]
