from django.urls import path

from .views import (
    CategoryCreateView,
    CategoryListView,
    DistributorProductListView,
    IngredientCreateView,
    ProductCreateView,
    ProductBottlePricesView,
    ProductCSVExportView,
    ProductDetailView,
    ProductListView,
    ProductPackageDeleteView,
    ProductPackageFormView,
    ProductRetailPricesView,
    ProductUpdateView,
    RetailPriceSheetView,
    ShopifyImportView,
)


urlpatterns = [
    path(
        "distributor/products/",
        DistributorProductListView.as_view(),
        name="distributor-product-list",
    ),
    path(
        "owner/products/categories/",
        CategoryListView.as_view(),
        name="category-list",
    ),
    path(
        "owner/products/categories/new/",
        CategoryCreateView.as_view(),
        name="category-create",
    ),
    path(
        "owner/products/ingredients/new/",
        IngredientCreateView.as_view(),
        name="ingredient-create",
    ),
    path(
        "owner/products/",
        ProductListView.as_view(),
        name="product-list",
    ),
    path(
        "owner/products/new/",
        ProductCreateView.as_view(),
        name="product-create",
    ),
    path(
        "owner/products/import/shopify/",
        ShopifyImportView.as_view(),
        name="product-shopify-import",
    ),
    path(
        "owner/products/export/",
        ProductCSVExportView.as_view(),
        name="product-csv-export",
    ),
    path(
        "owner/products/<uuid:pk>/",
        ProductDetailView.as_view(),
        name="product-detail",
    ),
    path(
        "owner/products/<uuid:pk>/bottle-prices/",
        ProductBottlePricesView.as_view(),
        name="product-bottle-prices",
    ),
    path(
        "owner/products/<uuid:pk>/retail-prices/",
        ProductRetailPricesView.as_view(),
        name="product-retail-prices",
    ),
    path(
        "owner/products/retail-price-sheet.csv",
        RetailPriceSheetView.as_view(),
        name="product-retail-price-sheet",
    ),
    path(
        "owner/products/<uuid:pk>/packages/new/",
        ProductPackageFormView.as_view(),
        name="product-package-create",
    ),
    path(
        "owner/products/<uuid:pk>/packages/<uuid:package_pk>/edit/",
        ProductPackageFormView.as_view(),
        name="product-package-edit",
    ),
    path(
        "owner/products/<uuid:pk>/packages/<uuid:package_pk>/delete/",
        ProductPackageDeleteView.as_view(),
        name="product-package-delete",
    ),
    path(
        "owner/products/<uuid:pk>/edit/",
        ProductUpdateView.as_view(),
        name="product-edit",
    ),
]
