# Generated by Django 5.2.17 on 2026-09-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='owner_viewed_at',
            field=models.DateTimeField(blank=True, help_text="When the Owner first opened this order. Null means it's new.", null=True),
        ),
    ]
