# Generated by Django 5.2.17 on 2026-09-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_purchaseorderpayment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pays_advance',
            field=models.BooleanField(blank=True, help_text='The Distributor\'s answer to "Are you paying in advance?" right after placing the order. Blank until answered.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderpayment',
            name='kind',
            field=models.CharField(choices=[('ADVANCE', 'Advance'), ('FINAL', 'Final')], default='FINAL', max_length=10),
        ),
    ]
