# Generated by Django 5.2.17 on 2026-10-01 09:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
from django.db.models import F


def copy_unit_price_to_list_price(apps, schema_editor):
    # Lines placed before agreements existed were sold at their unit
    # price with no discount.
    PurchaseOrderItem = apps.get_model("requests", "PurchaseOrderItem")
    PurchaseOrderItem.objects.update(list_price=F("unit_price"))



class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
        ('requests', '0004_advance_and_final_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text='The signed agreement in force on the day the order was placed. Its discounts pre-filled each line. Blank = list prices.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='agreements.agreement'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Starts at the agreement's discount for this product; the Owner can change it until the line ships.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="The product's price before any discount, when ordered.", max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='owner_note',
            field=models.TextField(blank=True, help_text="The Owner's comment on this product, shown to the Distributor."),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unavailable',
            field=models.BooleanField(default=False, help_text="The Owner can't supply the rest of this line. Whatever hasn't shipped is dropped from the order (and its total), so the order can complete without it."),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_SHIPPED', 'Partially shipped'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='list_price less discount_percentage.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.RunPython(copy_unit_price_to_list_price, migrations.RunPython.noop),
    ]
