# Generated by Django 5.2.17 on 2026-10-08 09:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_allergen_info_product_key_benefits_and_more'),
        ('requests', '0005_purchaseorder_agreement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='distributor_seen_revision',
            field=models.PositiveIntegerField(default=0, help_text='The last step of the conversation the Distributor has seen.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_number',
            field=models.CharField(blank=True, help_text="The Owner's invoice number, given when the invoice is issued: SI-<BRAND>-0001.", max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='owner_seen_revision',
            field=models.PositiveIntegerField(default=0, help_text='The last step of the conversation the Owner has seen.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_placed_at',
            field=models.DateTimeField(blank=True, help_text='When the Distributor accepted the quote and it became a Purchase Order.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quoted_at',
            field=models.DateTimeField(blank=True, help_text='When the Owner first answered the Request to Quote with prices.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='requested_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price the Distributor asked for on the Request to Quote (blank = asked the Owner to quote).', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, help_text='When the Owner issued the invoice.', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('QUOTE', 'Request to Quote'), ('PENDING', 'Pending'), ('PARTIALLY_SHIPPED', 'Partially shipped'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The current agreed price — list_price less discount_percentage. Blank only on a Request to Quote.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='PurchaseOrderRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('stage', models.CharField(choices=[('REQUEST', 'Request to Quote'), ('QUOTE', "Owner's quote"), ('COUNTER', "Distributor's counter-offer"), ('PURCHASE_ORDER', 'Purchase Order'), ('INVOICE', 'Invoice')], max_length=20)),
                ('by_owner', models.BooleanField(default=False, help_text='Said by the Owner (otherwise by the Distributor).')),
                ('message', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='purchase_order_revisions/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='requests.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['purchase_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderRevisionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Blank = no price given (please quote).', max_digits=18, null=True)),
                ('removed', models.BooleanField(default=False, help_text='This line was dropped from the order at this step.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='The live order line; blank once that line was dropped from the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_lines', to='requests.purchaseorderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='requests.purchaseorderrevision')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorderrevision',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'number'), name='unique_revision_number_per_purchase_order'),
        ),
    ]
