# Generated by Django 5.2.17 on 2026-09-17 10:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorprofile',
            name='upfront_payment_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="How much of a Purchase Order's total this Distributor must pay (and have it confirmed by the Owner) before the Owner can ship anything on it. 0 = pay only after receiving, 100 = pay in full before shipping, anything in between is a split (e.g. 30 = 30% before shipping, 70% after receiving).", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
