from django.urls import path

from .views import (
    CommentPurchaseOrderView,
    ConfirmPaymentView,
    DeclinePurchaseOrderView,
    DistributorOrdersHubView,
    DistributorPurchaseOrderAdvanceView,
    DistributorPurchaseOrderDetailView,
    DistributorPurchaseOrderListView,
    DistributorPurchaseOrderReceiveView,
    OwnerPurchaseOrderDetailView,
    OwnerPurchaseOrderListView,
    OwnerPurchaseOrdersHubView,
    PurchaseOrderCreateView,
    PurchaseOrderPDFView,
    RecordPaymentView,
    RejectPaymentView,
    ShipPurchaseOrderItemView,
    UpdateLineDiscountsView,
    UpdateLineStatusView,
    UpdatePricingView,
)


urlpatterns = [
    path(
        "distributor/orders/",
        DistributorOrdersHubView.as_view(),
        name="distributor-orders-hub",
    ),
    path(
        "distributor/purchase-orders/",
        DistributorPurchaseOrderListView.as_view(),
        name="distributor-purchase-order-list",
    ),
    path(
        "distributor/purchase-orders/new/",
        PurchaseOrderCreateView.as_view(),
        name="purchase-order-create",
    ),
    path(
        "distributor/purchase-orders/<uuid:pk>/",
        DistributorPurchaseOrderDetailView.as_view(),
        name="distributor-purchase-order-detail",
    ),
    path(
        "distributor/purchase-orders/<uuid:pk>/advance/",
        DistributorPurchaseOrderAdvanceView.as_view(),
        name="distributor-purchase-order-advance",
    ),
    path(
        "distributor/purchase-orders/<uuid:pk>/received/",
        DistributorPurchaseOrderReceiveView.as_view(),
        name="distributor-purchase-order-receive",
    ),
    path(
        "distributor/purchase-orders/<uuid:pk>/payments/",
        RecordPaymentView.as_view(),
        name="purchase-order-record-payment",
    ),
    path(
        "owner/purchase-orders-hub/",
        OwnerPurchaseOrdersHubView.as_view(),
        name="owner-purchase-orders-hub",
    ),
    path(
        "owner/purchase-orders/",
        OwnerPurchaseOrderListView.as_view(),
        name="owner-purchase-order-list",
    ),
    path(
        "owner/purchase-orders/<uuid:pk>/",
        OwnerPurchaseOrderDetailView.as_view(),
        name="owner-purchase-order-detail",
    ),
    path(
        "owner/purchase-orders/<uuid:pk>/items/<uuid:item_id>/ship/",
        ShipPurchaseOrderItemView.as_view(),
        name="purchase-order-item-ship",
    ),
    path(
        "owner/purchase-orders/<uuid:pk>/discounts/",
        UpdateLineDiscountsView.as_view(),
        name="purchase-order-update-discounts",
    ),
    path(
        "owner/purchase-orders/<uuid:pk>/items/<uuid:item_id>/status/",
        UpdateLineStatusView.as_view(),
        name="purchase-order-item-status",
    ),
    path(
        "owner/purchase-orders/<uuid:pk>/pricing/",
        UpdatePricingView.as_view(),
        name="purchase-order-update-pricing",
    ),
    path(
        "owner/purchase-orders/<uuid:pk>/decline/",
        DeclinePurchaseOrderView.as_view(),
        name="purchase-order-decline",
    ),
    path(
        "owner/purchase-orders/<uuid:pk>/comment/",
        CommentPurchaseOrderView.as_view(),
        name="purchase-order-comment",
    ),
    path(
        "owner/purchase-orders/<uuid:pk>/payments/<uuid:payment_id>/confirm/",
        ConfirmPaymentView.as_view(),
        name="purchase-order-payment-confirm",
    ),
    path(
        "owner/purchase-orders/<uuid:pk>/payments/<uuid:payment_id>/reject/",
        RejectPaymentView.as_view(),
        name="purchase-order-payment-reject",
    ),
    path(
        "purchase-orders/<uuid:pk>/pdf/",
        PurchaseOrderPDFView.as_view(),
        name="purchase-order-pdf",
    ),
]
